---
# esp04: basic sonoff.
#
# This ESPHome code is used on a Sonoff Basic.
# It controls nothing special, it is just a
# generic Sonoff connected to a power bar.
#
# I have it around for quickly hooking up something.
# For example, the christmas tree or some other
# temporary thing.
#
esphome:
  name: s3
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid1
  password: !secret wifi_password
# manual_ip:
#    static_ip: !secret esphome_s3_static_ip
#    gateway: !secret wifi_gateway
#    subnet: !secret wifi_subnet
#    dns1: !secret wifi_dns1
#    dns2: !secret wifi_dns2
  fast_connect: true

logger:

api:

ota:
 
sensor:
  - platform: wifi_signal
    name: esphome_s3_wifi_signal
    update_interval: 10s
  - platform: uptime
    name: esphome_s3_uptime

text_sensor:
  - platform: version
    name: esphome_s3_esphome_version

switch:
  - platform: restart
    name: esphome_s3_restart
  - platform: gpio
    name: shed_lights
    id: relay
    pin: GPIO12
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    output: green_led
    id: led